# Generated by Django 4.2.3 on 2023-11-03 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Parentesco')),
            ],
            options={
                'db_table': 'parentesco',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('clinica', models.CharField(max_length=100, verbose_name='Clínica')),
                ('leito', models.CharField(max_length=100, verbose_name='Leito')),
                ('nome', models.CharField(max_length=100, verbose_name='Visitante')),
                ('documento', models.CharField(max_length=100, verbose_name='Documento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcao_principal.parentesco', verbose_name='Parentesco')),
            ],
            options={
                'db_table': 'visitante',
            },
        ),
    ]
