# Generated by Django 4.2.3 on 2023-07-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100, verbose_name='Paciente')),
                ('data_registro_paciente', models.DateTimeField(auto_now=True, verbose_name='Data de Registro do Paciente')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhante', models.CharField(max_length=100, verbose_name='Acompanhante')),
                ('data_registro_acompanhante', models.DateTimeField(auto_now=True, verbose_name='Data de Registro do Acompanhante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'db_table': 'acompanhante',
            },
        ),
    ]
