# Generated by Django 4.2.3 on 2023-08-18 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("paciente", models.CharField(max_length=100, verbose_name="Paciente")),
                ("prontuario", models.AutoField(primary_key=True, serialize=False)),
                ("clinica", models.CharField(max_length=100, verbose_name="clinica")),
                ("leito", models.CharField(max_length=100, verbose_name="leito")),
                (
                    "comunicado_interno",
                    models.TextField(blank=True, null=True, verbose_name="C.I"),
                ),
                (
                    "data_registro_paciente",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Registro do Paciente"
                    ),
                ),
            ],
            options={
                "db_table": "paciente",
            },
        ),
        migrations.CreateModel(
            name="Parentesco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentesco",
                    models.CharField(max_length=100, verbose_name="Parentesco"),
                ),
            ],
            options={
                "db_table": "parentesco",
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_registro_visitante",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Registro do Visitante"
                    ),
                ),
                (
                    "visitante",
                    models.CharField(max_length=100, verbose_name="Visitante"),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Documento"
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "parentesco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.parentesco",
                        verbose_name="Parentesco",
                    ),
                ),
            ],
            options={
                "db_table": "visitante",
            },
        ),
    ]
