# Generated by Django 4.2.3 on 2023-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="prontuario",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
