# Generated by Django 4.2.3 on 2023-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_paciente_prontuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="clinica",
            field=models.CharField(max_length=100, verbose_name="Clinica"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="leito",
            field=models.CharField(max_length=100, verbose_name="Leito"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="prontuario",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Prontuário"
            ),
        ),
    ]
