# Generated by Django 4.2.3 on 2023-07-23 17:52

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_acompanhante_usuario_paciente_usuario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "bloco",
            },
        ),
        migrations.CreateModel(
            name="Enfermaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                (
                    "bloco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bloco"
                    ),
                ),
            ],
            options={
                "db_table": "enfermaria",
            },
        ),
        migrations.CreateModel(
            name="Leito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                (
                    "enfermaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.enfermaria",
                    ),
                ),
            ],
            options={
                "db_table": "leito",
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="bloco",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.bloco"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paciente",
            name="enfermaria",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="bloco",
                chained_model_field="bloco",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.enfermaria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paciente",
            name="leito",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="enfermaria",
                chained_model_field="enfermaria",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.leito",
            ),
            preserve_default=False,
        ),
    ]
