# Generated by Django 4.2.3 on 2023-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_parentesco_parentesco_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_registro_paciente',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='data_registro_visitante',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_registro',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Registro'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='data_registro',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Registro'),
        ),
    ]
