# Generated by Django 4.2.3 on 2023-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bloco_enfermaria_leito_paciente_bloco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloco',
            old_name='nome',
            new_name='bloco',
        ),
        migrations.RemoveField(
            model_name='enfermaria',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='leito',
            name='numero',
        ),
        migrations.AddField(
            model_name='enfermaria',
            name='enfermaria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leito',
            name='leito',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
