# Generated by Django 4.2.3 on 2023-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_bloco_bloco_remove_enfermaria_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhante',
            name='contato1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Contado (1)'),
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='contato2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Contado (2)'),
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
