# Generated by Django 4.2.3 on 2023-08-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_visitante_operador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Censo',
        ),
        migrations.AlterModelTable(
            name='censo',
            table='censo',
        ),
    ]
