# Generated by Django 4.2.3 on 2023-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acompanhante_contato1_acompanhante_contato2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhante',
            name='contato1',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Contado (1)'),
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='contato2',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Contado (2)'),
        ),
    ]
