# Generated by Django 4.2.3 on 2023-08-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_paciente_censo_alter_censo_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Censo',
            new_name='Interno',
        ),
        migrations.AlterModelTable(
            name='interno',
            table='interno',
        ),
    ]
