# Generated by Django 4.2.3 on 2023-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_paciente_internado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="visitante",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Registro"
            ),
        ),
    ]
