# Generated by Django 4.2.3 on 2023-08-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_censo_interno_alter_interno_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interno',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='paciente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='visitante',
            new_name='nome',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
    ]
