# Generated by Django 4.2.3 on 2023-07-24 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_acompanhante_contato1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vizitante', models.CharField(max_length=100, verbose_name='Vizitante')),
                ('data_registro_vizitante', models.DateTimeField(auto_now=True, verbose_name='Data de Registro do Vizitante')),
                ('contato1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Contado (1)')),
                ('contato2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Contado (2)')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'db_table': 'vizitante',
            },
        ),
    ]
