# Generated by Django 4.2.3 on 2023-07-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_vizitante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parentesco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentesco",
                    models.CharField(max_length=100, verbose_name="Parentesco"),
                ),
            ],
            options={
                "db_table": "parentesco",
            },
        ),
        migrations.AddField(
            model_name="acompanhante",
            name="parentesco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parentesco",
                verbose_name="Parentesco",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vizitante",
            name="parentesco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parentesco",
                verbose_name="Parentesco",
            ),
            preserve_default=False,
        ),
    ]
