# Generated by Django 4.2.3 on 2023-07-25 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_parentesco_acompanhante_parentesco_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paciente",
            unique_together={("bloco", "enfermaria", "leito")},
        ),
    ]
