# Generated by Django 4.2.3 on 2023-09-18 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_visitante_clinica_visitante_leito"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitante",
            name="clinica",
        ),
        migrations.RemoveField(
            model_name="visitante",
            name="leito",
        ),
    ]
