# Generated by Django 4.2.3 on 2023-07-25 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_alter_paciente_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_registro_visitante",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Registro do Visitante"
                    ),
                ),
                (
                    "visitante",
                    models.CharField(max_length=100, verbose_name="Visitante"),
                ),
                (
                    "contato1",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Contado (1)"
                    ),
                ),
                (
                    "contato2",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Contado (2)"
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "parentesco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.parentesco",
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "db_table": "visitante",
            },
        ),
        migrations.DeleteModel(
            name="Vizitante",
        ),
    ]
