# Generated by Django 4.2.3 on 2023-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_acompanhante_observacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acompanhante",
            name="contato1",
        ),
        migrations.RemoveField(
            model_name="acompanhante",
            name="contato2",
        ),
        migrations.RemoveField(
            model_name="visitante",
            name="contato1",
        ),
        migrations.RemoveField(
            model_name="visitante",
            name="contato2",
        ),
        migrations.AddField(
            model_name="paciente",
            name="comunicado_interno",
            field=models.TextField(blank=True, null=True, verbose_name="C.I"),
        ),
    ]
