"""
Django settings for MedNet project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from render_settings import render
from server_settings import server

is_server = True

if is_server:
    server()
else:
    render()
