# Generated by Django 4.2.3 on 2023-08-26 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parentesco",
            old_name="parentesco",
            new_name="tipo",
        ),
    ]
