# Generated by Django 4.2.3 on 2023-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_paciente_data_registro_paciente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitante",
            name="documento",
            field=models.CharField(default=1, max_length=100, verbose_name="Documento"),
            preserve_default=False,
        ),
    ]
