# Generated by Django 4.2.3 on 2023-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_visitante_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="internado",
            field=models.BooleanField(default=True),
        ),
    ]
