# Generated by Django 4.2.3 on 2023-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_paciente_data_registro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitante",
            name="clinica",
            field=models.CharField(default=1, max_length=100, verbose_name="Clínica"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visitante",
            name="leito",
            field=models.CharField(default=1, max_length=100, verbose_name="Leito"),
            preserve_default=False,
        ),
    ]
